name: Build GBAnalyzer

on: [ push ]

env:
  GHIDRA_VERSION: "11.0"
  GHIDRA_BUILD_DATE: 20231222
  GHIDRA_SHA256: f1f240f91cf6b1dffc9a4148384ee3c6b269a8ae27c6f981577973e00043ad94
  GHIDRA_INSTALL_DIR: /home/runner/ghidra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Install Ghidra
      run: .github/utils/install_ghidra.sh
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run:  gradle -PGHIDRA_INSTALL_DIR=/home/runner/ghidra  
    - uses: actions/upload-artifact@v4
      with:
        name: "GBAnalyzer_Plugin_${{env.GHIDRA_VERSION}}"
        path: dist/*GBAnalyzer.zip
        if-no-files-found: 'error'
